import { StyleSheet } from 'react-native';

export const getStyles = (theme) =>
  StyleSheet.create({
    container: { flex: 1, backgroundColor: theme.background },
    center: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: theme.background,
    },
    gridOverlay: {
      ...StyleSheet.absoluteFillObject,
      opacity: 0.05,
      borderColor: theme.primary,
      borderWidth: 1,
    },
    headerBox: {
      padding: 20,
      backgroundColor: theme.surface,
      borderBottomWidth: 1,
      borderColor: theme.primary,
    },
    userId: {
      color: theme.primary,
      fontSize: 10,
      fontFamily: 'Cyber-Regular',
      letterSpacing: 2,
      marginBottom: 15,
    },
    statsRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 20 },
    statValue: { color: theme.text, fontSize: 24, fontFamily: 'Cyber-Bold' },
    statLabel: { color: theme.primary, fontSize: 9, fontFamily: 'Cyber-Regular', letterSpacing: 1 },
    divider: { width: 1, height: 30, backgroundColor: theme.divider, marginHorizontal: 20 },
    barTrack: { height: 6, backgroundColor: theme.barTrack, marginTop: 5 },
    barFill: { height: '100%', backgroundColor: theme.primary },
    questCard: {
      marginHorizontal: 15,
      marginTop: 15,
      padding: 15,
      backgroundColor: theme.surface,
      borderLeftWidth: 3,
      borderLeftColor: theme.primary,
    },
    cardHeader: { flexDirection: 'row', justifyContent: 'space-between' },
    questTitle: { color: theme.text, fontSize: 14, fontFamily: 'Cyber-Bold' },
    questReward: {
      color: theme.textSecondary,
      fontSize: 11,
      marginTop: 8,
      fontFamily: 'Cyber-Regular',
    },
    energy: { color: theme.primary, fontSize: 14, fontFamily: 'Cyber-Bold' },
    fab: {
      position: 'absolute',
      right: 20,
      bottom: 30,
      width: 60,
      height: 60,
      backgroundColor: theme.primary,
      justifyContent: 'center',
      alignItems: 'center',
      shadowColor: theme.primary,
      shadowOpacity: 0.5,
      shadowRadius: 10,
      elevation: 5,
    },
    fabText: { fontSize: 30, fontFamily: 'Cyber-Bold', color: theme.background },
  });
